name: Claude - Auto-triage CVEs with Fix PR

# ABOUT
# - Inspects dependency manifests for likely CVEs/outdated packages, proposes safe upgrades on a new branch, optional PR.
# - Manual only; conservative by default.
#
# CUSTOMIZATION
# - Set package_manager for better guidance (npm/yarn/pnpm/pip/poetry/cargo/go/bundler).
# - Tighten the prompt to only allow patch/minor bumps.
# - Remove PR creation if you want to inspect changes first.

on:
  workflow_dispatch:
    inputs:
      package_manager:
        description: npm|yarn|pnpm|pip|poetry|cargo|go|bundler (used for guidance)
        required: false
        default: npm
      branch_name:
        description: Branch for dependency updates (e.g., chore/deps-cve-fixes)
        required: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  cve-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Triage vulnerable dependencies and create PR
        uses: anthropics/claude-code-action@beta
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: agent
          allowed_tools: |
            Write,
            Bash(git config:*),
            Bash(git checkout -b:*),
            Bash(git add:*),
            Bash(git commit:*),
            Bash(git push:*),
            Bash(gh pr create:*),
            Bash(mkdir -p reports)
          override_prompt: |
            You are a dependency upgrade assistant.

            Task:
            - Inspect dependency manifests and lockfiles.
            - Identify vulnerable or outdated packages with known CVEs (based on typical advisories for the indicated package manager: "${{ inputs.package_manager }}").
            - Prepare minimal, semver-safe upgrades. If a breaking change is likely, document it rather than performing the upgrade.
            - Create a new branch "${{ inputs.branch_name }}", commit updated lockfiles/manifests if safe.
            - Open a PR with a summary report in the body (reports/deps-cve-summary.md) listing risks and test notes.

            Safety:
            - Avoid broad version jumps unless necessary and justified.
            - If uncertain, prefer adding a TODO with instructions over making risky changes.
