name: Generate Poem with Claude

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger for testing

permissions:
  contents: write

jobs:
  generate-poem:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate unique seed
      id: seed
      run: |
        TIMESTAMP=$(date +%s%N)
        RANDOM_NUM=$RANDOM
        SEED="${TIMESTAMP}-${RANDOM_NUM}"
        echo "seed=$SEED" >> $GITHUB_OUTPUT
        echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
    
    - name: Generate poem with Claude
      uses: anthropics/claude-code-action@v1
      with:
        api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        prompt: |
          Generate a creative and unique poem. Use the seed "${{ steps.seed.outputs.seed }}" to ensure uniqueness.
          
          Requirements:
          1. Choose randomly from these styles: haiku (5-7-5 syllables), limerick (AABBA rhyme), sonnet (14 lines), free verse (4-8 lines), or rhyming couplet
          2. Choose a random theme from: nature, technology, love, time, dreams, ocean, mountains, stars, city, seasons, code, art, music, journey, or wisdom
          3. Create a unique title with format: "[Adjective] [Noun]" (e.g., "Golden Whisper", "Digital Dream")
          4. Make the poem creative, evocative, and meaningful
          5. Save the poem to a new file at path: poems/${{ steps.seed.outputs.timestamp }}_[title_lowercase_underscored].md
          
          The file should be formatted as:
          ```markdown
          # [Title]
          
          *Generated on [Current DateTime UTC]*  
          *Style: [Style Name]*  
          *Theme: [Theme Name]*  
          *Seed: ${{ steps.seed.outputs.seed }}*
          
          ---
          
          [Poem content here]
          
          ---
          
          *This poem was automatically generated by Claude via GitHub Actions*
          ```
          
          Create only one poem file. Make it unique and beautiful!