name: Generate Poem with Claude

on:
  # schedule:
  # Run every 15 minutes
  # - cron: "*/15 * * * *"
  workflow_dispatch: # Allow manual trigger for testing

# Permissions must be set to allow writing back to the repository.
permissions:
  contents: write
  id-token: write

jobs:
  generate-poem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate unique seed
        id: seed
        run: |
          TIMESTAMP=$(date +%s%N)
          RANDOM_NUM=$RANDOM
          SEED="${TIMESTAMP}-${RANDOM_NUM}"
          echo "seed=$SEED" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Generate poem with Claude
        uses: anthropics/claude-code-action@beta
        with:
          # Use 'agent' mode for scheduled/automated tasks that don't need a trigger.
          mode: agent
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # Explicitly grant Claude the tools to write a file and use git commands.
          allowed_tools: "Write,Bash(git add:*),Bash(git commit:*),Bash(git push),Bash(git pull),Bash(git config:*)"
          # Use 'override_prompt' for direct, automated instructions.
          override_prompt: |
            You are a creative poet bot. Your task is to generate a unique poem and commit it to this repository.

            First, configure git with the bot's identity:
            1. Run `git config user.name "github-actions[bot]"`
            2. Run `git config user.email "github-actions[bot]@users.noreply.github.com"`

            Next, generate the poem:
            - Use the seed "${{ steps.seed.outputs.seed }}" to ensure uniqueness.
            - Choose randomly from these styles: haiku (5-7-5 syllables), limerick (AABBA rhyme), sonnet (14 lines), free verse (4-8 lines), or rhyming couplet.
            - Choose a random theme from: nature, technology, love, time, dreams, ocean, mountains, stars, city, seasons, code, art, music, journey, or wisdom.
            - Create a unique title with the format: "[Adjective] [Noun]" (e.g., "Golden Whisper", "Digital Dream").
            - Write the poem to a new file at path: poems/${{ steps.seed.outputs.timestamp }}_[title_lowercase_underscored].md

            The file must be formatted exactly as follows:
            ```markdown
            # [Title]

            *Generated on [Current DateTime UTC]*
            *Style: [Style Name]*
            *Theme: [Theme Name]*
            *Seed: ${{ steps.seed.outputs.seed }}*

            ---

            [Poem content here]

            ---

            *This poem was automatically generated by Claude via GitHub Actions*
            ```

            Finally, commit the new poem file to the repository:
            1. Stage the new file using `git add poems/`.
            2. Commit the file with the message "feat: add poem '[Poem Title]'".
            3. Pull the latest changes using `git pull --rebase` to ensure you have the latest commits.
            4. Push the commit using `git push`.

            Execute these steps precisely.
