name: Claude - Secret Hygiene Coach

# ABOUT
# - Scans repo for potential secrets and writes a remediation guide. Read-only.
# - Manual only.
#
# CUSTOMIZATION
# - Adjust search_globs to match your file types.
# - Add/remove grep patterns in the prompt for your environment.
# - Consider adding an org-approved secret scanner link in the report for follow-up.

on:
  workflow_dispatch:
    inputs:
      search_globs:
        description: Globs to scan (comma-separated)
        required: false
        default: "**/*.env, **/*.yaml, **/*.yml, **/*.json, **/*.ts, **/*.js, **/*.py"

permissions:
  contents: read
  id-token: write

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for high-risk patterns and advise
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: agent
          allowed_tools: |
            Write,
            Bash(rg:*),
            Bash(grep:*),
            Bash(mkdir -p reports)
          override_prompt: |
            You are a secret hygiene assistant.

            Task:
            - Grep for likely secrets across globs: "${{ inputs.search_globs }}" using patterns (API_KEY, SECRET, PRIVATE KEY, tokens, passwords, AWS_*, etc.).
            - DO NOT rewrite history or change files.
            - Produce reports/secret-hygiene.md with findings and a remediation checklist (rotate keys, scrub history via manual steps, add detection to CI).

            Safety:
            - Read-only analysis. Only write the report.

      - name: Upload reports artifact
        if: ${{ hashFiles('reports/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: claude-reports
          path: reports/**
